<?php
$section  = 'site_color';
$priority = 1;

Kirki::add_field( 'tm-lawyers', array(
    'type'        => 'color',
    'setting'     => 'color',
    'label'       => esc_html__( 'Color', 'tm-lawyers' ),
    'description' => esc_html__( 'Choose a primary color for your site', 'tm-lawyers' ),
    'section'     => $section,
    'priority'    => $priority ++,
    'default'     => '#048FCB',
    'transport'   => 'postMessage',
    'output'      => array(
        array(
            'element'  => implode( ',', array(
                'a:hover',
                '.hentry .entry-header .entry-title a:hover',
                '.main-navigation .sub-menu li a:hover, .main-navigation .children li a:hover',
                '.site-footer a:hover',
                '.site-footer ul li a:before',
                '.site-footer .widget i',
                '.copyright a',
                '.header01 .site-header .site-header-right .site-header-right-content .site-header-right-content-inner .icon',
                '.header01 .site-header .site-header-right .site-header-right-content .site-header-right-content-inner a:hover',
                '.site-top-left i',
                '.tm_bread_crumb, .big-title .title-container ul li a, .big-title--single .title-container ul li a, .big-title .title-container ul li:before, .big-title--single .title-container ul li:before',
                '.hentry .entry-meta i',
                '.single-post .hentry .entry-footer i',
                '.single-post .hentry .entry-footer a:hover',
                '.tmlawyer_contact_keepintouch i',
                '.history .date',
                '.skill .value',
                '.tmlawyer_textbox_1 ul li:before',
                '.main-navigation .sub-menu li.current-menu-item a, .main-navigation .children li.current-menu-item a',
                '.home_intro .home_intro_icon .icon',
                '.tm_lawyers_testimonials .author span:first-child',
                '.popup-search .inner .content .box .popup-search-close:hover',
                '.site-footer .widget .widget-title:before',
                '.heading_center:after, .heading_left:after',
                '.sidebar .widget .widget-title:after, .wpb_widgetised_column .widget .widget-title:after',
                '.header02 .site-header .site-header-right .site-header-right-content .site-header-right-content-inner .icon',
                '.header03 .site-header .site-header-info-content .textwidget i',
                '.header04 .site-top a:hover',
                '.header04 .site-top .social-menu ul li a:hover:before',
                '.tmlawyer_accordion .vc_tta-panels-container .vc_tta-panels .vc_tta-panel .vc_tta-panel-heading .vc_tta-panel-title i',
                '.sidebar .widget.widget_categories ul li a:before, .sidebar .widget.better-menu-widget ul li a:before, .wpb_widgetised_column .widget.widget_categories ul li a:before, .wpb_widgetised_column .widget.better-menu-widget ul li a:before',
            ) ),
            'property' => 'color',
        ),
        array(
            'element'  => implode( ',', array(
                '.main-navigation',
                '.scrollup',
                '.newsletter .social-menu ul.menu li a:hover',
                '.newsletter input[type="submit"]',
                '.social-menu ul.menu li a:hover',
                '.tmlawyer_contact_form3 input[type="submit"]',
                '.pagination span.current, .pagination span:hover, .pagination a:hover',
                '.sidebar .widget.widget_tag_cloud .tagcloud a:hover, .wpb_widgetised_column .widget.widget_tag_cloud .tagcloud a:hover',
                '.tmlawyer_contact_form input[type="submit"], .tmlawyer_contact_form2 input[type="submit"]',
                '.memberinfo .memberinfo_social a:hover',
                '.memberinfo .memberinfo_contact .memberinfo_contact_icon i',
                '.header02 .site-header .site-header-info .site-header-info-content div.info-content i',
                '.header03 .main-navigation:after',
                '.header04 .site-header .site-header-info .site-header-info-content div.info-content i',
                '.single-post .comments-area button, .single-post .comments-area input[type=button], .single-post .comments-area input[type=submit], .page .comments-area button, .page .comments-area input[type=button], .page .comments-area input[type=submit]',
            ) ),
            'property' => 'background-color',
        ),
        array(
            'element'  => implode( ',', array(
                '.vc_icon_element.vc_icon_element-outer .vc_icon_element-inner.vc_icon_element-size-md .vc_icon_element-icon',
                '.vc_icon_element.vc_icon_element-outer .vc_icon_element-inner .vc_icon_element-icon:before',
                '.sidebar .widget a:hover, .wpb_widgetised_column .widget a:hover',
                '.sidebar .widget.widget_tm_lawyers_postswidget .postswidget-list .postswidget-info .title a:hover, .wpb_widgetised_column .widget.widget_tm_lawyers_postswidget .postswidget-list .postswidget-info .title a:hover',
                '.sidebar .widget.widget_tm_lawyers_postswidget .postswidget-list .postswidget-info .time i, .sidebar .widget.widget_tm_lawyers_postswidget .postswidget-list .postswidget-info .comment i, .sidebar .widget.widget_tm_lawyers_postswidget .postswidget-list .postswidget-info .like i, .wpb_widgetised_column .widget.widget_tm_lawyers_postswidget .postswidget-list .postswidget-info .time i, .wpb_widgetised_column .widget.widget_tm_lawyers_postswidget .postswidget-list .postswidget-info .comment i, .wpb_widgetised_column .widget.widget_tm_lawyers_postswidget .postswidget-list .postswidget-info .like i',
            ) ),
            'property' => 'color',
            'suffix'   => ' !important',
        ),
        array(
            'element'  => implode( ',', array(
                '.tmlawyer_button_1 a, .tmlawyer_button_1 button',
            ) ),
            'property' => 'background-color',
            'suffix'   => ' !important',
        ),
        array(
            'element'  => implode( ',', array(
                '.tmlawyer_icon_1 .vc_icon_element-inner',
            ) ),
            'property' => 'border-color',
            'suffix'   => ' !important',
        ),
    ),
) );
